//Get products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

//Get product search
export const GET_PRODUCT_SEARCH_SUCCESS = "GET_PRODUCT_SEARCH_SUCCESS";
export const GET_PRODUCT_SEARCH_FAILED = "GET_PRODUCT_SEARCH_FAILED";
export const GET_PRODUCT_SEARCH_LOADING = "GET_PRODUCT_SEARCH_LOADING";

//Get single product
export const GET_PRODUCT_SINGLE_SUCCESS = "GET_PRODUCT_SINGLE_SUCCESS";
export const GET_PRODUCT_SINGLE_FAILED = "GET_PRODUCT_SINGLE_FAILED";

//Get Reviews by product
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";

//Get selling product
export const GET_SELLING_SUCCESS = "GET_SELLING_SUCCESS";
export const GET_SELLING_FAILED = "GET_SELLING_FAILED";